### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by kasitoru** [GollumDom/addon-repository#1]
Raspberry Pi 4 (Home Assistant OS 6.6, core-2021.11.3, supervisor-2021.10.8, aarch64)
> Can't install smeagolworms4/mqtt-explorer:latest: 404 Client Error for http+docker://localhost/v1.41/images/smeagolworms4/mqtt-explorer:latest/json: Not Found ("no such image: smeagolworms4/mqtt-explorer:latest: No such image: smeagolworms4/mqtt-explorer:latest")

**Comment by Smeagolworms4** [comment]
But https://hub.docker.com/r/smeagolworms4/mqtt-explorer existe. Can try docker pull smeagolworms4/mqtt-explorer before install

**Comment by kasitoru** [comment]
Maybe there is no container for the arm64 architecture?

**Comment by Smeagolworms4** [comment]
![image](https://user-images.githubusercontent.com/4448640/141819543-52190801-cdf8-4170-968d-f106986794fe.png)

I use on RPI 4 with ARM/V7 version and works

**Comment by kasitoru** [comment]
For RPI4 version 8GB, the entire amount of RAM is not available in 32-bit mode. 64 bit is needed, but there is no mqtt-explorer container for it (see my screenshot).

**Comment by Smeagolworms4** [comment]
I add linux/arm64/v8 on build : https://github.com/Smeagolworms4/MQTT-Explorer/runs/4214505300?check_suite_focus=true

**Comment by Smeagolworms4** [comment]
but crash waiting dockerhub is unstable this evening

**Comment by kasitoru** [comment]
Not urgent. As it turns out, let me know here. I'll test it. Thanks!

**Comment by Smeagolworms4** [comment]
https://github.com/Smeagolworms4/MQTT-Explorer/runs/4214749947?check_suite_focus=true

**Comment by Smeagolworms4** [comment]
This running working

**Comment by Smeagolworms4** [comment]
Done

**Comment by kasitoru** [comment]
Great! It works!
